TYPO3:
  Neos:

    modules:
      management:
        submodules:
          googleAnalytics:
            label: 'Analytics'
            controller: 'TYPO3\Neos\GoogleAnalytics\Controller\OverviewController'
            description: 'Google Analytics overview and management'
            icon: 'icon-bar-chart'
            resource: 'TYPO3_Neos_GoogleAnalytics_Module_Management_Overview'

    GoogleAnalytics:
      # Configure the P12 key file location (relative to FLOW_PATH)
      keyFileResource: ~
