TYPO3:
  Neos:

    userInterface:
      requireJsPathMapping:
        'TYPO3.Neos.GoogleAnalytics/Inspector/Editors': 'resource://TYPO3.Neos.GoogleAnalytics/Public/Scripts/Inspector/Editors'

    typoScript:
      autoInclude:
        'TYPO3.Neos.GoogleAnalytics': TRUE

    modules:
      management:
        submodules:
          googleAnalytics:
            label: 'Analytics'
            controller: 'TYPO3\Neos\GoogleAnalytics\Controller\OverviewController'
            description: 'Google Analytics overview and management'
            icon: 'icon-bar-chart'
            resource: 'TYPO3_Neos_GoogleAnalytics_Module_Management_Overview'

    GoogleAnalytics:
      authentication:
        # Application name for the consent screen
        applicationName: 'TYPO3 Neos'
        # Client ID of the webapplication OAuth 2.0 credential
        clientId: ~
        # Client secret of the webapplication OAuth 2.0 credential
        clientSecret: ~
        # Api Key of the Public API Access credential
        developerKey: ~

      stats:
        basic:
          metrics: 'ga:pageviews,ga:sessions,ga:users'
        usersByUserType:
          metrics: 'ga:users'
          dimensions: 'ga:userType'
        sessionsByDeviceCategory:
          metrics: 'ga:sessions'
          dimensions: 'ga:deviceCategory'
        loadTimes:
          metrics: 'ga:avgPageLoadTime,ga:avgServerResponseTime'
